### ISSUE TITLE
Network connect failed

### ISSUE THREAD

**Issue by MdFahimulIslam** [myDevicesIoT/Cayenne-MQTT-ESP8266#12]
I'm using NodeMCU. 

I tried to upload this example code from here: 
File > Example > Cayenne-MQQTT-ESP > esp8266
with proper ssid[], wifiPassword[],  username[], password[] and clientID[].

But the serial monitor shows: 

$€ÿ€ÿ-Süþ[765] Connecting to TechShop 2G
[18766] Connected to WiFi
[18767] IP: 192.168.137.90
[18767] Connecting to mqtt.mydevices.com:1883
[25060] Network connect failed
[32384] Network connect failed
[39684] Network connect failed
[47008] Network connect failed
...
![2018-06-07 10_47_01-com23](https://user-images.githubusercontent.com/24982795/41078847-ef79dbf8-6a40-11e8-9dbc-f3da8f75064d.png)

And the dashboard shows "waiting for board to connect".
Tried your getting sarted video on youtube. Didn't work. using the same ssid and wifiPassword i was able to connect to blynk app but unable to do so with Cayenne.

**Comment by jburhenn** [comment]
That could potentially be some issue on the server side with verifying your MQTT credentials. You might try re-adding the device via the dashboard and use the new MQTT credentials to try again.

You could also try the [Cayenne-MQTT-Arduino](https://github.com/myDevicesIoT/Cayenne-MQTT-Arduino) library which is a little newer and now has support for ESP8266/NodeMCU. You can install that via the Arduino Library Manager. The library is called CayenneMQTT in the Library Manager. You might need to remove the currently installed Cayenne-MQTT-ESP library and restart the Arduino IDE to prevent any possible library incompatibility issues.
