### ISSUE TITLE
If begin failed, hang. 

### ISSUE THREAD

**Issue by bestpika** [myDevicesIoT/Cayenne-MQTT-ESP8266#6]
If `Cayenne.begin()` failed, board will hang at [here](https://github.com/myDevicesIoT/Cayenne-MQTT-ESP8266/blob/51e9a0bd06531870c4430d8765199eb78e191c9c/src/CayenneArduinoMQTTClient.h#L69).
Could it add retry times and return t/f?

**Comment by jburhenn** [comment]
We could look into doing that, though it probably won't be too high priority since the client can't send any data until the connection happens. So we designed it to keep trying in case there is a server/network issue. That way the client will automatically reconnect when the issue is resolved.
