### ISSUE TITLE
Add a parameter to the CayenneMQTTWiFiClient.h to define the already established wifi client name.

### ISSUE THREAD

**Issue by rcojoe** [myDevicesIoT/Cayenne-MQTT-ESP8266#7]
Right now,  the wifi client variable name is WiFi, which isn't too complex to do a find and replace all the "client" in my sketch to "WiFi".

**Comment by jburhenn** [comment]
I'm not sure I understand the issue. Do you mean you aren't using the WiFi instance specified via ESP8266WiFi.h? You are including some other WiFi class instead? How are you including that?

**Comment by rcojoe** [comment]
You may be referring to the method: 
* Begins Cayenne session and in the process establishes a WIFI connection with the supplied ssid and WIFI password on line 32.  


I"m referring to this method:
* Begins Cayenne session, assumes that the WIFI is already up and running. on line 64.  

Here I have already declared the class and called it something other than WiFi, in my case, I called it "client"
For example,  outside of the Cayenne code, I have:
WiFiClient client;

**Comment by rcojoe** [comment]
But now I understand that this may be a fallback call if the mqtt server disconnects, and just needs to be reconnected.  I thought it was an alternate call method.  I'm using ArduinoOTA, which uses a preexisting connection, and i'm using another mqtt library currently that uses the declartion like this to indicate the wifi connection: 
PubSubClient MQTTclient(client);

**Comment by rcojoe** [comment]
Its my lack of understand that is at fault here.  I thought the wifi class had to be declared using a different name, like the wifisecure class is instated.  This is an invalid issue.

**Comment by jburhenn** [comment]
Glad you were able to get it working.
